#!/bin/sh

# docker run --rm -t -v /root/dev-tmp:/tmp -v /root/build:/build genee/phpize

PHP_VERSION_ID=$(echo '<?= PHP_VERSION_ID ?>'|php5)
BUILD_DIR=/build/php-$PHP_VERSION_ID

mkdir -p $BUILD_DIR

# install redis
[ ! -d /tmp/phpredis ] && git clone https://github.com/phpredis/phpredis.git /tmp/phpredis
cd /tmp/phpredis && \
    phpize && ./configure && make && make install && \
    cp /usr/lib/php/modules/redis.so $BUILD_DIR

# install yaml
[ ! -d /tmp/yaml ] && git clone https://github.com/php/pecl-file_formats-yaml.git /tmp/yaml
cd /tmp/yaml && \
    phpize && ./configure && make && make install && \
    cp /usr/lib/php/modules/yaml.so $BUILD_DIR

# install zmq
[ ! -d /tmp/zmq ] && git clone https://github.com/mkoppanen/php-zmq.git /tmp/zmq
cd /tmp/zmq && \
    phpize && ./configure && make && make install && \
    cp /usr/lib/php/modules/zmq.so $BUILD_DIR

# install uopz
[ ! -d /tmp/uopz ] && git clone https://github.com/krakjoe/uopz.git /tmp/uopz
cd /tmp/uopz && \
    git checkout PHP5 && phpize && ./configure && make && make install && \
    cp /usr/lib/php/modules/uopz.so $BUILD_DIR

# install friso
[ ! -d /tmp/friso ] && git clone https://git.oschina.net/lionsoul/friso.git /tmp/friso
cd /tmp/friso/src && make && make install && cp /usr/lib/libfriso.so $BUILD_DIR

ldconfig
cd /tmp/friso/vendors/binding/php5 && phpize && ./configure && \
    make && make install && cp /usr/lib/php/modules/friso.so $BUILD_DIR

# install xdebug
[ ! -d /tmp/xdebug ] && git clone https://github.com/xdebug/xdebug.git /tmp/xdebug
cd /tmp/xdebug && \
    phpize && ./configure && make && make install && \
    cp /usr/lib/php/modules/xdebug.so $BUILD_DIR
