#!/bin/sh

# docker run --rm -it -v /tmp/php7-build:/tmp -v /root/build:/build -v $PWD/app/alpine:/app genee/phpize build7

PHP_VERSION_ID=$(echo '<?= PHP_VERSION_ID ?>'|php7)
BUILD_DIR=/build/php-$PHP_VERSION_ID

mkdir -p $BUILD_DIR

# build redis
apk add php7-session
[ ! -d /tmp/phpredis ] && git clone https://github.com/phpredis/phpredis.git /tmp/phpredis
cd /tmp/phpredis && git reset --hard && git checkout master && git pull --rebase --autostash && git checkout 4.0.2 \
    && phpize7 && ./configure --with-php-config=/usr/bin/php-config7 && make && make install && \
    cp /usr/lib/php7/modules/redis.so $BUILD_DIR

# build yaml
apk add yaml-dev
[ ! -d /tmp/yaml ] && git clone https://github.com/php/pecl-file_formats-yaml.git /tmp/yaml
cd /tmp/yaml && git reset --hard && git checkout master && git pull --rebase --autostash && git checkout 2.0.2 \
    && phpize7 && ./configure --with-php-config=/usr/bin/php-config7 && make && make install && \
    cp /usr/lib/php7/modules/yaml.so $BUILD_DIR

# build zmq
apk add zeromq-dev
[ ! -d /tmp/zmq ] && git clone https://github.com/mkoppanen/php-zmq.git /tmp/zmq
cd /tmp/zmq && git reset --hard && git checkout master && git pull --rebase --autostash && git checkout php7 \
    && phpize7 && ./configure --with-php-config=/usr/bin/php-config7 && make && make install && \
    cp /usr/lib/php7/modules/zmq.so $BUILD_DIR

# build uopz
# [ ! -d /tmp/uopz ] && git clone https://github.com/krakjoe/uopz.git /tmp/uopz
# cd /tmp/uopz && git reset --hard && git checkout master && git pull --rebase --autostash && git checkout v5.0.1 \
#    && phpize7 && ./configure --with-php-config=/usr/bin/php-config7 && make && make install && \
#    cp /usr/lib/php7/modules/uopz.so $BUILD_DIR

# build xdebug
[ ! -d /tmp/xdebug ] && git clone https://github.com/xdebug/xdebug.git /tmp/xdebug
cd /tmp/xdebug && git reset --hard && git checkout master && git pull --rebase --autostash && git checkout XDEBUG_2_5_5 \
    && phpize7 && ./configure --with-php-config=/usr/bin/php-config7 \
    && make && make install && cp /usr/lib/php7/modules/xdebug.so $BUILD_DIR

# build friso
[ ! -d /tmp/friso ] && git clone https://git.oschina.net/lionsoul/friso.git /tmp/friso
cd /tmp/friso/src && git reset --hard && git checkout master && git pull --rebase --autostash \
    && make && make install && cp /usr/lib/libfriso.so $BUILD_DIR

ldconfig
cd /tmp/friso/vendors/binding/php7 \
    && phpize7 && ./configure --with-php-config=/usr/bin/php-config7 \
    && make && make install && cp /usr/lib/php7/modules/friso.so $BUILD_DIR

# build swoole
apk add linux-headers
[ ! -d /tmp/swoole ] && git clone https://github.com/swoole/swoole-src.git /tmp/swoole
cd /tmp/swoole && git reset --hard && git checkout master && git pull --rebase --autostash \
    && phpize7 && ./configure --with-php-config=/usr/bin/php-config7 \
    && make && make install && cp /usr/lib/php7/modules/swoole.so $BUILD_DIR

